### PR TITLE
 Migrate tests towards JUnit 5

### PR DESCRIPTION
**Pull request by juliette-derancourt**
## Summary

Migration of the JUnit tests from version 4 to 5.

## Details

- Replace annotations (Test, Before, After...)
- Remove useless public scopes
- Replace SpringRunner by SpringExtension

## Todo

Replace TemporaryFolder rule by build-in [TempDir](https://junit.org/junit5/docs/current/user-guide/#writing-tests-built-in-extensions-TempDirectory) in [GitRebaserTest](https://github.com/societe-generale/ci-droid-tasks-consumer/blob/4592334328af660f43eebeb09c42c6ac67221335/ci-droid-tasks-consumer-infrastructure/src/test/java/com/societegenerale/cidroid/tasks/consumer/infrastructure/GitRebaserTest.java) (last remaining usage of JUnit 4).
The issue is that when I use TempDir it doesn't clean the test files and it messes with the repo's files... I don't know what's happening, but I'm also wondering if this test could not be refactored a little to make things clearer ^^
Once we do that, it will be possible to remove the junit-vintage artifact.

### CODE REVIEW

**Comment by vincent-fuchs** [comment]
I am trying to reproduce locally, but I have issues with the versions. junit-jupiter 5.4.0 pulls junit-jupiter-api 5.3.2. TempDir doesn't seem to exist there. 

can you push your target code, with the failing test ? It will be easier for me to have a look at fixing the test.

Thanks

**Comment by vincent-fuchs** [comment]
arf, sorry about the conflicts - I just merged your older PR with codacy violation fixes, so all the files that are touched in both PRs now have a conflict here.

**Comment by juliette-derancourt** [comment]
> arf, sorry about the conflicts - I just merged your older PR with codacy violation fixes, so all the files that are touched in both PRs now have a conflict here.

No worries ;)

> I am trying to reproduce locally, but I have issues with the versions. junit-jupiter 5.4.0 pulls junit-jupiter-api 5.3.2. TempDir doesn't seem to exist there.

Yes I had the same problem, I just realized that spring-boot-starter-parent pulls the 5.3.2 and it's somehow ignoring the version I specified

> can you push your target code, with the failing test ? It will be easier for me to have a look at fixing the test.

Actually, the test is not failing. The issue is that when you're in your local repo, launching it will create a ton of files an mess with git (I guess that since the test is running some rebases, it's interfering with the actual repository).
I pushed the code if you want to try and see :)

**Comment by juliette-derancourt** [comment]
Sorry I forgot about this, but I just tried again to run GitRebaserTest and I see two problems afterwards:
- The temp files are not deleted (testFile1.txt and testFile2.txt)
- More importantly, a git repository is created inside the infrastructure folder: there's a .git folder at the root

That being said, I don't really understand every aspects of this test class either... Why is there several temp directories created in different ways?

**Comment by vincent-fuchs** [comment]
OK, I confirm I now understand both issues - all this should happen in target folder. I'll have a look, thanks for raising that issue

**Comment by vincent-fuchs** [comment]
I've raised #65 - I think I'll merge it, unless you have other views.

**Comment by vincent-fuchs** [comment]
taken care  of in https://github.com/societe-generale/ci-droid-tasks-consumer/pull/65

**Pull request closed without merging**
